namespace Game.Logic.CardEffect
{
    public enum eCardEffectType
    {
        AntCave,
        GuluKingdom2,
        GuluKingdom4,
        EvilTribe3,
        EvilTribe5,
        ShadowDevil2,
        ShadowDevil4,
        FourArtifacts2,
        FourArtifacts4,
        Goblin2,
        Goblin4,
        Goblin5,
        RunRunChicken2,
        RunRunChicken4,
        GuluSportsMeeting2,
        GuluSportsMeeting4,
        GuluSportsMeeting5,
        FiveGodSoldier2,
        FiveGodSoldier5,
        TimeVortex3,
        TimeVortex5,
        WarriorsArena3,
        WarriorsArena5,
        PioneerDeck,
        WeaponMasterDeck,
        DivineDeck,
        LuckyDeck,
        HappinessDeck,
        LegendaryWeaponDeck,
        AresDeck
    }
}
