namespace Game.Server.Statics
{
    public enum LogMoneyType
	{
Auction = 1,
        Auction_Update = 101,
        Award = 8,
        Award_Answer = 804,
        Award_BossDrop = 805,
        Award_Daily = 801,
        Award_Drop = 803,
        Award_Quest = 802,
        Award_TakeCard = 806,
        Box = 9,
        Box_Open = 901,
        Consortia = 5,
        Consortia_Rich = 412,
        Charge = 7,
        Charge_RMB = 701,
        Game = 10,
        Game_Boos = 1001,
        Game_Other = 1004,
        Game_PaymentTakeCard = 1002,
        Game_Shoot = 1005,
        Game_TryAgain = 1003,
        Item = 6,
        Item_Color = 602,
        Item_Move = 601,
        Mail = 2,
        Mail_Money = 201,
        Mail_Pay = 202,
        Mail_Send = 203,
        Marry = 4,
        Marry_Flower = 408,
        Marry_Follow = 404,
        Marry_Gift = 403,
        Marry_Hymeneal = 410,
        Marry_Room = 406,
        Marry_RoomAdd = 407,
        Marry_Spark = 401,
        Marry_Stage = 402,
        Marry_Unmarry = 405,
        Shop = 3,
        Shop_Buy = 301,
        Shop_Card = 303,
        Shop_Continue = 302,
        Shop_Present = 304	}
}
