namespace Game.Logic.Protocol
{
    public enum eFightPackageType
	{
CHANGE_GAME_TYPE = 72,
        CHAT = 19,
        DISCONNECT = 83,
        DISCONNECT_PLAYER = 34,
        FIGHT_NPC = 88,
        FIND_CONSORTIA_ALLY = 77,
        FOOTBALL_TAKE_OUT = 87,
        KIT_OFF_PLAYER = 4,
        LOG_FIGHT = 5,
        LOGIN = 1,
        PLAYER_ADD_ACTIVE_MONEY = 89,
        PLAYER_ADD_GOLD = 38,
        PLAYER_ADD_GP = 39,
        PLAYER_ADD_GIFTTOKEN = 75,
        PLAYER_ADD_HEALSTONE = 73,
        PLAYER_ADD_ITEM = 37,
        PLAYER_ADD_LEAGUEMONEY = 84,
        PLAYER_ADD_MEDAL = 76,
        PLAYER_ADD_MONEY = 74,
        PLAYER_ADD_OFFER = 51,
        PLAYER_ADD_PRESTIGE = 85,
        PLAYER_ADD_ROBRICHES = 52,
        PLAYER_ADD_TEMPLATE = 46,
        PLAYER_ADD_TEMPLATE1 = 48,
        PLAYER_CLEAR_BAG = 53,
        PLAYER_CONSORTIAFIGHT = 42,
        PLAYER_ON_GAME_OVER = 35,
        PLAYER_ONKILLING_LIVING = 40,
        PLAYER_ONMISSION_OVER = 41,
        PLAYER_REMOVE_GOLD = 44,
        PLAYER_REMOVE_GP = 49,
        PLAYER_REMOVE_MONEY = 45,
        PLAYER_REMOVE_OFFER = 50,
        PLAYER_SEND_CONSORTIAFIGHT = 43,
        PLAYER_UPDATE_REST_COUNT = 86,
        PLAYER_USE_PROP_INGAME = 36,
        REMOVE_PLAYER = 70,
        ROOM_CREATE = 0x40,
        ROOM_REMOVE = 65,
        ROOM_START_GAME = 66,
        ROOM_STOP_GAME = 68,
        RSAKey = 0,
        SEND_GAME_PLAYER_ID = 33,
        SEND_TO_GAME = 2,
        SEND_TO_GAME_ALL_PLAYER = 71,
        SEND_TO_ROOM = 67,
        SEND_TO_USER = 0x20,
        SYS_NOTICE = 3,
        UPDATE_ROOM_ID = 69,
        UpdateRoom = 69	}
}
