namespace Game.Logic
{
    public enum eEffectType
    {
        AddAgilityEffect = 1,
        AddAttackEffect = 2,
        AddBloodEffect = 3,
        AddBombEquipEffect = 24,
        AddDamageEffect = 4,
        AddDander = 20,
        AddDefenceEffect = 5,
        AddGuardEquipEffect = 39,
        AddLuckyEffect = 6,
        AddTurnEquipEffect = 19,
        ArmorPiercer = 17,
        AssimilateBloodEffect = 28,
        AssimilateDamageEffect = 27,
        AtomBomb = 0x10,
        AvoidDamageEffect = 25,
        ContinueDamageEffect = 23,
        ContinueReduceBaseDamageEffect = 36,
        ContinueReduceBaseDamageEquipEffect = 30,
        ContinueReduceBlood = 40,
        ContinueReduceBloodEffect = 33,
        ContinueReduceBloodEquipEffect = 0x20,
        ContinueReduceDamageEffect = 38,
        ContinueReduceGreenBloodEffect = 1001,
        DamageEffect = 41,
        FatalEffect = 7,
        GuardEffect = 42,
        HideEffect = 8,
        IceFronzeEffect = 9,
        IceFronzeEquipEffect = 10,
        InvinciblyEffect = 11,
        LockDirectionEffect = 35,
        LockDirectionEquipEffect = 34,
        MakeCriticalEffect = 26,
        NoHoleEffect = 12,
        NoHoleEquipEffect = 13,
        PhongAn = 1000,
        RecoverBloodEffect = 37,
        ReduceDamageEffect = 14,
        ReduceStrengthEffect = 22,
        ReduceStrengthEquipEffect = 0x1F,
        ReflexDamageEffect = 29,
        ReflexDamageEquipEffect = 21,
        SealEffect = 0xF,
        SealEquipEffect = 18,
        AddTargetEffect = 44,
        AddBloodTurnEffect = 45,
        AddDamageTurnEffect = 46,
        AddGuardTurnEffect = 47
    }
}
